let components = [
  'commodityStats/commodityStats',
  'salesStats/salesStats',
  'salesStats/salesStats2',
  'salesStats/salesStats3',
  'salesStats/salesStats4',
  'userOrders/userOrders',
  'userStats/userStats',
  'jgssalesStats/jgssalesStats',
  'jurisdictionOutsideAddrAdmin/addrAdmin',
  'prodManage/List',
  'prodManage/Info',
  'guestorder/List',
  'guestorder/Info',
  'shopOrder/List',
  'shopOrder/Info',
  'goodsTag/goodsTag',
  'goodsData/goodsData',
  'goodsData/goodsUpdate',
  'goodsData/goodsDetail',
  'goodsData/newGoodsData',
  'priceManagent/priceManagent',
  'priceManagent/applyMgr',
  'priceManagent/priceCheck',
  'priceManagent/priceRecord',
  'filterCrowd/filterCrowd',
  'claimsRecord/List',
  'claimsRecord/Info',
  'claimsRuls/claimsRuls',
  'insuranceRecord/index',
  'insuranceRecord/Details',
  'claimCalculation/calculation',
  'claimCalculation/calculationRefund'
];

module.exports = components;
